# 激活 dev 开发环境
spring:
  profiles:
    active: dev

---

# dev 开发环境配置
spring:
    profiles: dev
    application:
        name: microservice-config-dev

---

# test 测试环境配置
spring:
  profiles: test
  application:
    name: microservice-config-test
