spring:
  profiles:
    active:
    - dev

---

server: 
  port: 8000 
spring:
  profiles: dev
  application: 
    name: config-client-dev

---

server: 
  port: 9000 
spring:
  profiles: test
  application: 
    name: config-client-test
