spring:
  profiles:
    active:
    - dev
---

server: 
  port: 8000 
spring:
  profiles: dev
  application: 
    name: config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001:7001/eureka/

---

server: 
  port: 9000 
spring:
  profiles: test
  application: 
    name: config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7002:7002/eureka/
 

